apiVersion: v1
kind: Service
metadata:
  name: greet-app-service
spec:
  type: NodePort
  selector:
    app: greet-app
  ports:
    - protocol: TCP
      port: 5000       
      targetPort: 5000 
      nodePort: 30000